name: Deploy to Netlify on commits to master
on:
  workflow_run:
     workflows: ["Test using Jest"]
     types: [completed]
jobs:
  tests-succeeded:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.19.1

      - name: Install Dependencies
        run: npm install

      - name: Build site
        run: CI=false npm run build
        
      - name: Set Netlify env variable CI
        run: netlify env:set CI False
        
      - name: Set Netlify env variable NODE_VERSION
        run: netlify env:set NODE_VERSION 14.19.1

      # Deploy the site with netlify-cli
      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        run: netlify deploy --prod
  test-failed:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "Test with Jest failed"
